export const cuisineList = {
  african: "African",
  american: "American",
  australian: "Australian",
  british: "British",
  caribbean: "Caribbean",
  chinese: "Chinese",
  french: "French",
  fusion: "Fusion",
  german: "German",
  greek: "Greek",
  indian: "Indian",
  irish: "Irish",
  italian: "Italian",
  japanese: "Japanese",
  kerala: "Kerala",
  korean: "Korean",
  latinamerican: "Latin American",
  mediterranean: "Mediterranean",
  mexican: "Mexican",
  middleeastern: "Middle Eastern",
  scottish: "Scottish",
  spanish: "Spanish",
  thai: "Thai",
  vietnamese: "Vietnamese",
};

export const mealTypes = {
  breakfast: "Breakfast",
  lunch: "Lunch",
  dinner: "Dinner",
  snacks: "Snacks",
};